# Generated by Django 5.2.10 on 2026-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriILAP',
            fields=[
                ('id_kategori', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID Kategori')),
                ('nama_kategori', models.CharField(max_length=50, verbose_name='Nama Kategori')),
            ],
            options={
                'verbose_name': 'Kategori ILAP',
                'verbose_name_plural': 'Kategori ILAP',
                'db_table': 'kategori_ilap',
            },
        ),
    ]
